# Generated by Django 2.1.5 on 2019-01-20 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import email_service.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_recipients', email_service.fields.EmailStringField(default='')),
                ('cc_list', email_service.fields.EmailStringField(null=True)),
                ('bcc_list', email_service.fields.EmailStringField(null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('body', models.TextField(null=True)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('from_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
