# Generated by Django 2.1.5 on 2019-01-25 20:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_service', '0002_auto_20190125_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailModel',
            new_name='Email',
        ),
    ]
